spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    baseline-on-migrate: true

server:
  port: 8989

management:
  endpoints:
    web:
      exposure:
        include: "*"

health:
  check:
    message: book service is up now local!!!

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest